version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  COVERALLS_REPO_TOKEN:
    secure: bN4xtacEwhnd2agRdX4jcr0Yk1zIyIYGwAiPwg7TW8E45V+n1hixAJgDjTS3pdh1
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: >-
    nuget restore -verbosity quiet

    nuget install coveralls.net -Version 0.7.0 -OutputDirectory tools  -verbosity quiet

    nuget install -OutputDirectory tools OpenCover -Version 4.6.519  -verbosity quiet
build:
  project: PrereleaseAttributes.sln
  verbosity: minimal
test_script:
- ps: >-
    $adapterFilePath = ".\packages\NUnit3TestAdapter.3.7.0\tools"


    Write-Host $adapterFilePath


    VSTest.Console.exe /logger:Appveyor /inIsolation /Enablecodecoverage /TestAdapterPath:"$adapterFilePath" .\Tests\bin\Release\Tests.dll .\PRI.PrereleaseAttributes.Analyzer\PRI.PrereleaseAttributes.Analyzer.Test\bin\Release\PRI.PrereleaseAttributes.Analyzer.Test.dll /Settings:CodeCoverage.runsettings


    $coverageFilePath = Resolve-Path -path "TestResults\*\*.coverage"

    $coverageFilePath = $coverageFilePath.ToString()


    if(Test-Path .\coverage.coveragexml){ rm .\coverage.coveragexml }


    ."C:\Program Files (x86)\Microsoft Visual Studio 12.0\Team Tools\Dynamic Code Coverage Tools\CodeCoverage.exe" analyze /output:coverage.coveragexml "$coverageFilePath"


    Push-AppveyorArtifact coverage.coveragexml


    $coveralls = (Resolve-Path "./tools/coveralls.net.*/tools/csmacnz.coveralls.exe").ToString()


    & $coveralls --dynamiccodecoverage -i coverage.coveragexml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID --useRelativePaths -o cov.json


    Push-AppveyorArtifact cov.json
artifacts:
- path: .\PRI.PrereleaseAttributes.Analyzer\PRI.PrereleaseAttributes.Analyzer\**\*.nupkg
  name: Nuget
deploy:
- provider: NuGet
  api_key:
    secure: K+dA1tJ3qNFfJ6G484VCFE9igeHb/BGa6tdJVKcaxvHYK6rwPsKrO/c5EahHvxsP
  artifact: Nuget
  on:
    branch: master